version: '3.8'

services:
  db:
    image: mysql
    restart: unless-stopped
    container_name: iths
    environment:
      MYSQL_DATABASE: "iths"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"